FROM ubuntu:24.04

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG http_proxy=${HTTP_PROXY}    
ARG https_proxy=${HTTP_PROXY}

ARG ZH_CN
ENV ZH_CN=${ZH_CN}

# Change the Ubuntu package mirror
RUN apt update && apt install -y apt-transport-https ca-certificates
RUN if [ "${ZH_CN}" = "true" ]; then \
        sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources && \
        sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources && \
        apt clean; \
    fi
  
# 设置非交互模式
ARG DEBIAN_FRONTEND=noninteractive

# 更新和安装必要的包
RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    rustc \
    cargo \
    sudo \
    && apt-get install -y nix \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN chmod 777 /tmp
# Users
##############
# Add a new user
ARG USER_ID=1000
ARG GROUP_ID=1000
ENV USER_ID=${USER_ID}
ENV GROUP_ID=${GROUP_ID}

RUN userdel $(getent passwd ${USER_ID} | cut -d: -f1) || true
RUN groupdel $(getent group ${GROUP_ID} | cut -d: -f1) || true
RUN groupadd -g ${GROUP_ID} user && \
    useradd -u ${USER_ID} -rm -d /home/user -s /usr/bin/bash -g user -G sudo user -p "$(openssl passwd -1 user)" && \
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Use user as default username
USER user
WORKDIR /home/user
ENV HOME=/home/user
# 下载 tlspuffin 最新源代码
RUN git clone https://github.com/tlspuffin/tlspuffin /home/user/tlspuffin
WORKDIR /home/user/tlspuffin
RUN sudo nix-shell