[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]