FROM ubuntu:24.04

ARG ZH_CN
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTP_PROXY}
ARG MAKE_OPT="-j4"

ENV ZH_CN=${ZH_CN}

ENV no_proxy="localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8"
ENV NO_PROXY=${no_proxy}

RUN apt update && apt install -y apt-transport-https ca-certificates
RUN if [ "${ZH_CN}" = "true" ]; then \
        sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources && \
        sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources && \
        apt clean; \
    fi

# ---------- LLVM-17 ----------
RUN apt update && apt install -y --no-install-recommends wget gnupg2 && rm -rf /var/lib/apt/lists
RUN echo deb http://apt.llvm.org/lunar/ llvm-toolchain-lunar-17 main >> /etc/apt/sources.list
RUN echo deb-src http://apt.llvm.org/lunar/ llvm-toolchain-lunar-17 main >> /etc/apt/sources.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

# ---------- 依赖安装 ----------
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && yes | unminimize && apt upgrade -y && \
    apt install -y \
    clang-17 llvm-17 llvm-17-dev lldb-17 lld-17 \
    apt-utils git build-essential mold curl libc++-dev sudo libtool libtool-bin libz-dev libglib2.0-dev graphviz-dev bison flex automake libpixman-1-dev cgroup-tools \
    cmake bear autoconf pkg-config gdb strace \
    openssh-server openssl libssl-dev libgnutls28-dev \
    libcap-dev libpcap-dev tcpdump \
    rsync autopoint gperf texinfo gettext \
    vim nano screen htop man wget httpie bash-completion ripgrep iputils-ping iproute2 telnet net-tools ncat netcat-traditional \
    graphviz graphviz-dev lsof gpg \
    libsqlite3-dev libelf-dev libc6-dbg gettext libtool gettext-base cmake-curses-gui \
    libcurl4-openssl-dev libjson-c-dev libpcre2-dev \
    pkg-config autoconf automake autotools-dev libev-dev libcunit1 gnupg \
    libstdc++-13-dev \
    && rm -rf /var/lib/apt/lists

RUN ln -sf /usr/bin/clang-17 /usr/bin/clang && \
    ln -sf /usr/bin/clang++-17 /usr/bin/clang++ && \
    ln -sf /usr/bin/llvm-config-17 /usr/bin/llvm-config

RUN if [ "${ZH_CN}" = "true" ]; then \
        pip3 install --break-system-packages -i https://mirrors.aliyun.com/pypi/simple gcovr; \
    else \
        pip3 install --break-system-packages gcovr; \
    fi

RUN chmod 777 /tmp

RUN if [ "${HTTP_PROXY}" != "" ]; then \
        echo "Acquire::http::Proxy \"${HTTP_PROXY}\";" > /etc/apt/apt.conf.d/99proxy && \
        echo "Acquire::ftp::Proxy \"${HTTP_PROXY}\";" >> /etc/apt/apt.conf.d/99proxy && \
        echo "Acquire::https::Proxy \"${HTTP_PROXY}\";" >> /etc/apt/apt.conf.d/99proxy; \
    fi

# ---------- 用户与权限 ----------
ARG USER_ID=1000
ARG GROUP_ID=1000
ENV USER_ID=${USER_ID}
ENV GROUP_ID=${GROUP_ID}

RUN userdel $(getent passwd ${USER_ID} | cut -d: -f1) || true
RUN groupdel $(getent group ${GROUP_ID} | cut -d: -f1) || true
RUN groupadd -g ${GROUP_ID} user && \
    useradd -u ${USER_ID} -rm -d /home/user -s /usr/bin/bash -g user -G sudo user -p "$(openssl passwd -1 user)" && \
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER user
WORKDIR /home/user
ENV HOME=/home/user

RUN if [ "${ZH_CN}" = "true" ]; then \
        git config --global url."https://gh-proxy.com/github.com/".insteadOf "https://github.com/"; \
    fi

RUN git config --global http.version HTTP/1.1 && \
    git config --global user.name Kherrisan && \
    git config --global user.email zdkscope@qq.com

COPY patches /tmp/patches

RUN git clone https://github.com/QUICTester/QUIC-Fuzz.git quic-fuzz
RUN cd quic-fuzz/aflnet && \
    make clean all && \
    cd llvm_mode && \
    make ${MAKE_OPT}
RUN cd quic-fuzz/SnapFuzz/SaBRe/plugins && \
    ln -sf ../../snapfuzz snapfuzz && \
    cd ../ && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DSF_MEMFS=OFF -DSF_STDIO=ON -DSF_SLEEP=ON -DSF_SMARTDEFER=OFF .. && \ 
    make ${MAKE_OPT} && \
    mv plugins/snapfuzz/libsnapfuzz.so plugins/snapfuzz/libsnapfuzz_no_snap.so && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DSF_MEMFS=OFF -DSF_STDIO=ON -DSF_SLEEP=ON -DSF_SMARTDEFER=ON .. && \
    make ${MAKE_OPT} && \
    cd ../../.. && \
    ln -sf SnapFuzz/SaBRe/build/sabre sabre && \
    ln -sf SnapFuzz/SaBRe/build/plugins/snapfuzz/libsnapfuzz.so libsnapfuzz.so && \
    ln -sf SnapFuzz/SaBRe/build/plugins/snapfuzz/libsnapfuzz_no_snap.so libsnapfuzz_no_snap.so

COPY scripts/gcov_preload.c gcov_preload.c
RUN gcc -shared -fpic gcov_preload.c -g -o libgcov_preload.so && \
    sudo touch "/etc/ld.so.conf.d/gcov.conf" && \
    echo "${HOME}" | sudo tee "/etc/ld.so.conf.d/gcov.conf" && \
    sudo ldconfig

COPY scripts/fake_random.c fake_random.c
RUN gcc -shared -fpic fake_random.c -g -o libfake_random.so && \
    sudo touch "/etc/ld.so.conf.d/fake_random.conf" && \
    echo "${HOME}" | sudo tee "/etc/ld.so.conf.d/fake_random.conf" && \
    sudo ldconfig

RUN echo "kernel.randomize_va_space = 0" | sudo tee -a /etc/sysctl.d/01-disable-aslr.conf && \
    sudo sysctl -p /etc/sysctl.d/01-disable-aslr.conf
