name: pingu-env-aflnet CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/Dockerfile-env-aflnet'
    tags:
      - v*
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/Dockerfile-env-aflnet'

jobs:    
  push:
    env:
      IMAGE_NAME: pingu-env-aflnet
      DOCKER_CLI_EXPERIMENTAL: enabled
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check if Dockerfile was modified
        id: check_files
        uses: tj-actions/changed-files@v35
        with:
          files: scripts/Dockerfile-env-aflnet
      - name: Build the Docker image
        if: steps.check_files.outputs.any_changed == 'true' && startsWith(github.ref, 'refs/tags/v')
        run: ./scripts/build-env.sh -f aflnet -- --build-arg GITHUB_TOKEN=${{ secrets.ZDK_GH_TOKEN }}
      - name: Log in to registry
        if: steps.check_files.outputs.any_changed == 'true' && startsWith(github.ref, 'refs/tags/v')
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        if: steps.check_files.outputs.any_changed == 'true' && startsWith(github.ref, 'refs/tags/v')
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker manifest create $IMAGE_ID:$VERSION $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
